ALTER TABLE balance_log ADD ACTUAL_AMOUNT BIGINT(20) NULL DEFAULT NULL COMMENT '实际收款金额=收款金额-平台手续费';
ALTER TABLE customer ADD WECHAT_ID VARCHAR(50) NULL DEFAULT NULL COMMENT '微信id';
ALTER TABLE customer ADD ALIPAY VARCHAR(50) NULL DEFAULT NULL COMMENT '支付宝账号';
ALTER TABLE customer ADD BANK_CARD VARCHAR(50) NULL DEFAULT NULL COMMENT '银行卡账户';

CREATE TABLE `inout` (
	`TIMESTAMP` BIGINT(20) NOT NULL,
	`OID` VARCHAR(45) NULL DEFAULT NULL,
	`CID` BIGINT(20) NOT NULL,
	`SIDE` VARCHAR(45) NULL DEFAULT NULL,
	`PNSGID` BIGINT(20) NULL DEFAULT NULL,
	`PNSID` BIGINT(20) NULL DEFAULT NULL,
	`QUANT` BIGINT(20) NULL DEFAULT NULL,
	`TRANID` VARCHAR(64) NULL DEFAULT NULL,
	`STATUS` VARCHAR(45) NULL DEFAULT NULL,
	PRIMARY KEY (`TIMESTAMP`, `CID`),
	UNIQUE INDEX `OID_UNIQUE` (`OID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT