ALTER TABLE balance_log ADD ACTUAL_AMOUNT BIGINT(20) NULL DEFAULT NULL COMMENT '实际收款金额=收款金额-平台手续费';
ALTER TABLE balance_log ADD WECHAT_ID VARCHAR(50) NULL DEFAULT NULL COMMENT '微信id';
ALTER TABLE balance_log ADD ALIPAY VARCHAR(50) NULL DEFAULT NULL COMMENT '支付宝账号';
ALTER TABLE balance_log ADD BANK_CARD VARCHAR(50) NULL DEFAULT NULL COMMENT '银行卡账户';