ALTER TABLE customer ADD WECHAT_ID VARCHAR(50) NULL DEFAULT NULL COMMENT '微信id';
ALTER TABLE customer ADD ALIPAY VARCHAR(50) NULL DEFAULT NULL COMMENT '支付宝账号';
ALTER TABLE customer ADD BANK_CARD VARCHAR(50) NULL DEFAULT NULL COMMENT '银行卡账户';